### ISSUE TITLE
move all content relevant to issue_manager to here

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/issue_manager#1]
- all the code
- all the macro's & portal pages
- documentation

basically anything public

remark
- DO NOT MOVE PRIVATE INFO e.g., passwds, keys, ...

**Comment by xmonader** [comment]
We got issuemanager app working again with portal9.

**Comment by xmonader** [comment]
Code now is separated into OVC like structure 
apps/IssueManager "with all the wikipages and macros" the portal app directory to be linked under /opt/jumpscale9/apps/portals/main/base/IssueManager

libs/issuemanagerlib for Capnp models and issuemanager functionality

**Comment by rkhamis** [comment]
We should also move the sychronization logic here and out of the gogs and github clients.

**Comment by xmonader** [comment]
Will be working on moving the sync logic to lssuemanagerlib

**Comment by xmonader** [comment]
Gogs/Github clients are moved to sync package 
https://github.com/Jumpscale/issue_manager/commit/a131c521ba094aa7e32ea52360ca78b582fe1687
